name: Linting

on:
  push:
    paths:
      - "**.py"
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            # super-linter needs the full git history to get the
            # list of files that changed across commits
            fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install flake8
      - name: Lint with flake8
        if: github.event_name == 'push'
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 \
          --select=C,E,F,W,B,B950 \
          --ignore=E123,E133,E226,E241,E242,F811,F601,W503,W504,E203,E501 \
          --per-file-ignores='**/init.py:F401' \
          --exclude=__unported__,__init__.py,examples \
          --show-source --statistics --count --max-line-length=120 .
      - uses: super-linter/super-linter@v7.1.0
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: ^__init__\.py|examples
  pylint:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - run: curl https://raw.githubusercontent.com/iterativo-git/dockerdoo/12.0/.devcontainer/.vscode/oca_pylint.cfg -o oca_pylint.cfg
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install pylint_odoo
      - run: |
          pylint **/*.py --exit-zero --rcfile oca_pylint.cfg --load-plugins pylint_odoo
